spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

telegram:
  bot:
    token: "6400518028:AAGD0fOmoxIrO7Y0IjunIhS5BsHvz8AlHJ4"
    username: "CurrencyTelegramExampleBot"

binance:
  api:
    getPrice: "https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT"
    updateFriquency: 2
    sendMessageFriquency: 10